[2021-11-04 11:42:51,705] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_login
[2021-11-04 11:42:55,817] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_add
[2021-11-04 11:42:58,814] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2021-11-04 11:43:02,552] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_edit
[2021-11-04 11:43:05,984] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_relation
[2021-11-04 11:43:09,298] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_remove
[2021-11-04 11:43:12,540] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_delete
[2021-11-04 11:43:14,724] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_section_search_clear
[2021-11-04 11:43:25,928] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_code_abnormal_001
[2021-11-04 11:43:28,473] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_code_abnormal_002
[2021-11-04 11:43:30,894] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_code_abnormal_002
[2021-11-04 11:43:33,449] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_code_abnormal_003
[2021-11-04 11:43:35,864] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_code_abnormal_004
[2021-11-04 11:43:38,314] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_name_abnormal_001
[2021-11-04 11:43:40,782] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_name_abnormal_002
[2021-11-04 11:43:43,526] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_name_abnormal_003
[2021-11-04 11:43:45,978] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_name_abnormal_003
[2021-11-04 11:43:48,432] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_name_abnormal_004
[2021-11-04 11:43:50,960] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_edit_name_abnormal_001
[2021-11-04 11:43:54,508] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_edit_name_abnormal_002
[2021-11-04 11:43:58,222] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_edit_name_abnormal_003
[2021-11-04 11:44:01,761] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_edit_name_abnormal_003
[2021-11-04 11:44:05,361] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_edit_name_abnormal_004
[2021-11-04 11:44:23,882] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_add
[2021-11-04 11:44:26,454] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_search
[2021-11-04 11:44:56,107] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_edit
[2021-11-04 11:45:01,590] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_relation
[2021-11-04 11:45:04,887] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_remove
[2021-11-04 11:45:08,254] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_delete
[2021-11-04 11:45:08,445] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_section_search_clear
[2021-11-04 11:45:20,866] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_code_abnormal_001
[2021-11-04 11:45:23,442] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_code_abnormal_002
[2021-11-04 11:45:26,060] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_code_abnormal_002
[2021-11-04 11:45:28,689] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_code_abnormal_003
[2021-11-04 11:45:31,217] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_code_abnormal_004
[2021-11-04 11:45:33,842] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_name_abnormal_001
[2021-11-04 11:45:36,463] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_name_abnormal_002
[2021-11-04 11:45:39,328] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_name_abnormal_003
[2021-11-04 11:45:41,950] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_name_abnormal_003
[2021-11-04 11:45:44,579] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_name_abnormal_004
[2021-11-04 11:45:47,248] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_edit_name_abnormal_001
[2021-11-04 11:45:50,874] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_edit_name_abnormal_002
[2021-11-04 11:45:54,788] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_edit_name_abnormal_003
[2021-11-04 11:45:58,344] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_edit_name_abnormal_003
[2021-11-04 11:46:01,929] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_company_edit_name_abnormal_004
[2021-11-04 11:46:14,503] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_factory_add
[2021-11-04 11:46:17,052] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_factory_search
[2021-11-04 11:46:18,737] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_factory_edit
[2021-11-04 11:46:21,566] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_factory_relation
[2021-11-04 11:46:24,957] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_factory_remove
[2021-11-04 11:46:28,279] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_factory_delete
[2021-11-04 11:46:29,449] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_section_search_clear
[2021-11-04 11:47:43,979] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_area_login
[2021-11-04 11:48:17,941] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
