[2022-02-18 09:06:54,228] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:07:01,665] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:07:12,104] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:07:15,978] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:07:19,789] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:07:24,843] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:07:47,572] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:08:29,589] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:09:11,659] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:09:16,835] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:09:18,554] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:09:20,199] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:09:21,426] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:09:21,490] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:09:23,734] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:09:53,346] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:10:36,693] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:10:39,392] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:10:43,142] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:10:44,835] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:10:46,041] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:10:46,163] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:10:52,112] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:11:33,585] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:12:33,531] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:12:34,967] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:12:36,902] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:12:46,861] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:12:53,290] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:12:53,407] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:13:01,991] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:13:02,087] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:13:48,098] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:13:51,271] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:13:53,961] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:13:55,634] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:13:56,873] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:13:56,996] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:14:05,377] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:14:05,556] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:14:33,788] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:14:39,003] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:15:20,436] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:15:28,886] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:16:07,625] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:16:11,457] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:16:14,046] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:16:14,849] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:16:15,651] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:16:16,446] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:16:17,322] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:16:19,144] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:16:19,655] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:16:20,463] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:16:21,271] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:16:43,177] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:17:25,148] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:18:07,115] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:18:49,146] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:19:31,296] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:20:13,314] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:20:55,519] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:21:37,476] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:22:19,310] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:23:01,161] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:23:43,349] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:24:25,272] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 09:27:19,199] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:28:01,299] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:28:43,367] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:29:14,523] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:31:58,308] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:31:59,946] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:32:00,750] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:32:01,524] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:32:02,283] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:32:03,086] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:32:03,861] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:32:05,639] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:32:06,144] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:32:06,866] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:32:07,719] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:32:10,668] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:32:13,551] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:32:16,487] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:32:19,205] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:32:22,137] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:32:25,142] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:32:28,077] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:32:30,960] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:32:33,835] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:32:36,656] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:32:39,525] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:32:42,474] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 09:33:02,681] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:33:05,550] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:33:08,428] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:33:11,369] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:33:49,651] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:33:53,998] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:33:55,660] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:34:16,167] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:34:16,291] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:34:18,629] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:35:00,034] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:35:41,576] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:38:18,185] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:38:21,073] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:38:22,686] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:38:24,331] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:38:24,424] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:38:26,715] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:38:35,291] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:38:35,380] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:44:45,600] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:44:52,741] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:44:57,553] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:45:02,233] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 09:45:06,960] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:45:11,675] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:45:17,387] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:45:22,415] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:45:27,096] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:48:07,282] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:48:11,108] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:48:27,471] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:48:28,917] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:48:32,000] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:48:34,757] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 09:48:36,246] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:48:36,300] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:48:44,801] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:48:44,924] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:48:45,003] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:49:48,268] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:49:52,410] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:49:54,035] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:49:55,656] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 09:49:57,217] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:49:57,299] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:50:05,576] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:50:05,704] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:50:05,754] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:51:05,787] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:51:08,932] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:51:12,015] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:51:13,641] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 09:51:15,243] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:51:15,346] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:51:23,711] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:51:23,859] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:51:23,947] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:51:52,872] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:51:54,557] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:51:55,535] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:51:56,451] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:51:57,273] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:51:58,080] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:51:58,948] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:52:00,813] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:52:01,335] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:52:02,067] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:52:02,825] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:52:05,879] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:52:08,732] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:52:11,610] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:52:14,522] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:52:17,233] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:52:20,241] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:52:23,219] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:52:26,170] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:52:29,080] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:52:31,948] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:52:34,829] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:52:37,885] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 09:52:57,739] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:53:00,677] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:53:03,555] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:53:06,544] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:53:36,280] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 09:53:49,018] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_auth
[2022-02-18 09:53:52,898] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_auth
[2022-02-18 09:53:55,157] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 09:53:56,230] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:53:57,900] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 09:53:59,504] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 09:54:01,074] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 09:54:01,163] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 09:54:09,752] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 09:54:13,623] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 09:54:13,689] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 09:54:19,536] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:54:20,164] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:54:21,009] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 09:54:21,866] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:54:22,715] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:54:23,617] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 09:54:24,508] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 09:54:26,380] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:54:46,810] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:55:07,121] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 09:55:10,819] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:55:13,905] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:55:16,807] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 09:55:19,609] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:55:22,476] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:55:25,355] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:55:28,325] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:55:31,321] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 09:55:34,205] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:55:36,988] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:55:39,768] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:55:42,683] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 09:55:45,563] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 09:56:06,708] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:56:09,639] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:56:12,622] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:56:15,630] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 09:56:25,012] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_usergp
[2022-02-18 09:56:46,185] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_setauth_usergp
[2022-02-18 09:56:50,013] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_usergp
[2022-02-18 09:56:53,980] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_usergp
[2022-02-18 09:56:57,953] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 09:57:04,198] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_user
[2022-02-18 09:57:16,018] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_user
[2022-02-18 09:57:20,820] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_active_user
[2022-02-18 09:57:27,082] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lock_user
[2022-02-18 09:57:32,522] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_unlock_user
[2022-02-18 09:57:37,933] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 09:58:00,433] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 09:58:03,186] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 09:58:24,961] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 09:58:32,652] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 09:58:35,550] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 09:58:38,455] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 09:58:41,303] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 09:58:44,230] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 09:58:47,069] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 09:58:49,931] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 09:58:53,376] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 09:59:00,997] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 09:59:07,477] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 09:59:13,882] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 09:59:19,970] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 09:59:25,570] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 09:59:31,410] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 09:59:37,370] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 09:59:43,280] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 09:59:49,289] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 09:59:50,367] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 10:04:54,928] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:04:56,715] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:04:57,748] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:04:58,719] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:04:59,633] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:05:00,600] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:05:01,500] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:05:07,565] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:05:08,172] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:05:08,979] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:05:09,853] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:05:12,993] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:05:15,920] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:05:18,892] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:05:21,952] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:05:24,917] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:05:27,986] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:05:31,020] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:05:33,987] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:05:36,942] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:05:39,956] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:05:42,978] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:05:46,080] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:06:06,940] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:06:09,883] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:06:12,884] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:06:15,929] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:06:42,135] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 10:06:48,492] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:06:53,397] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 10:06:57,350] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 10:07:10,410] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 10:07:14,613] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:07:16,672] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 10:07:18,336] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 10:07:19,900] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 10:07:20,000] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 10:07:28,309] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 10:07:28,466] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 10:07:28,569] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 10:08:14,060] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:08:34,273] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:08:40,518] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:08:46,970] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:08:53,358] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:08:59,638] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:09:05,882] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:09:12,390] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 10:09:18,572] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:09:24,834] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:09:31,089] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:09:37,344] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:09:43,601] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:09:49,872] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 10:09:56,144] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:10:02,156] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:10:07,927] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:10:13,886] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:10:19,799] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:10:25,687] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 10:10:29,072] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 10:13:51,871] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:13:58,001] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_user
[2022-02-18 10:14:09,348] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_user
[2022-02-18 10:14:14,193] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_active_user
[2022-02-18 10:14:20,572] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lock_user
[2022-02-18 10:14:25,970] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_unlock_user
[2022-02-18 10:14:31,398] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 10:15:05,429] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:15:12,753] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:15:19,235] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:15:25,798] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:15:32,331] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:15:38,879] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:15:45,374] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:15:51,886] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 10:15:58,354] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:16:04,730] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:16:11,221] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:16:17,673] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:16:24,186] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:16:30,663] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 10:16:36,801] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:16:42,436] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:16:48,217] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:16:54,024] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:16:59,936] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:17:05,857] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 10:17:09,774] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 10:20:10,092] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 10:20:22,620] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_auth
[2022-02-18 10:20:26,313] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_auth
[2022-02-18 10:20:28,540] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 10:20:29,654] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:20:31,329] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 10:20:32,933] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 10:20:34,540] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 10:20:34,604] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 10:20:43,069] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 10:20:46,952] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 10:20:47,021] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 10:20:52,780] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:20:53,404] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:20:54,234] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:20:55,066] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:20:55,890] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:20:56,668] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:20:57,546] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:21:00,551] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:21:20,804] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:21:41,146] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:22:01,433] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:22:04,217] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:22:07,173] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:22:10,161] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:22:13,131] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:22:16,069] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:22:18,986] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:22:21,919] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:22:24,867] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:22:27,757] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:22:30,653] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:22:33,554] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:22:36,543] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:24:15,401] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:24:18,357] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:24:21,334] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:24:24,376] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:24:33,668] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_usergp
[2022-02-18 10:24:55,352] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_setauth_usergp
[2022-02-18 10:24:59,153] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_usergp
[2022-02-18 10:25:02,976] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_usergp
[2022-02-18 10:25:06,823] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:25:13,324] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_user
[2022-02-18 10:25:22,691] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_user
[2022-02-18 10:25:27,444] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_active_user
[2022-02-18 10:25:33,774] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lock_user
[2022-02-18 10:25:39,301] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_unlock_user
[2022-02-18 10:25:44,666] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 10:26:07,239] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:26:10,111] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:26:15,291] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:26:21,816] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:26:28,224] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:26:34,786] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:26:41,333] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 10:26:47,730] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 10:26:54,254] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:27:00,702] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:27:07,197] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:27:13,674] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:27:20,157] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 10:27:26,728] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 10:27:32,801] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:27:38,419] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:27:44,244] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:27:50,101] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:27:56,100] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 10:28:02,039] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 10:28:05,846] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 10:36:15,095] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 10:36:27,773] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_auth
[2022-02-18 10:36:31,521] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_auth
[2022-02-18 10:36:33,835] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 10:36:34,936] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:36:36,601] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 10:36:38,221] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 10:36:39,752] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 10:36:39,822] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 10:36:48,263] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 10:37:08,723] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 10:37:08,791] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 10:37:13,555] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:37:14,187] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:37:14,992] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:37:15,929] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:37:16,794] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:37:17,594] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:37:18,448] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:37:21,361] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:37:33,181] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:37:33,943] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:37:34,714] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:37:37,703] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:37:40,601] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:37:43,483] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:37:46,356] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:37:49,169] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:37:51,979] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:37:54,917] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:37:57,775] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:38:00,552] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:38:03,449] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:38:06,672] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:38:09,561] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:39:49,044] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:39:52,020] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:39:54,918] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:39:57,850] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:40:45,311] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_usergp
[2022-02-18 10:40:48,438] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_setauth_usergp
[2022-02-18 10:40:52,186] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_usergp
[2022-02-18 10:40:55,910] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_usergp
[2022-02-18 10:41:10,176] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:45:21,435] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 10:45:34,109] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_auth
[2022-02-18 10:45:37,879] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_auth
[2022-02-18 10:45:40,131] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 10:45:41,227] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:45:42,877] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 10:45:53,282] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_002
[2022-02-18 10:45:54,846] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 10:45:54,921] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 10:46:03,324] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 10:46:07,225] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 10:46:07,323] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 10:46:12,103] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:46:12,760] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:46:13,556] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:46:14,404] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:46:15,201] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:46:16,049] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:46:16,880] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:46:19,720] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:46:29,662] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:46:30,433] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:46:31,199] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:46:34,249] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:46:37,023] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:46:39,870] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:46:42,800] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:46:45,673] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:46:48,603] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:46:51,507] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:46:54,486] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:46:57,300] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:47:00,160] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:47:03,004] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:47:05,902] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:47:35,055] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:47:37,947] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:47:40,829] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:47:43,782] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:48:31,010] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_usergp
[2022-02-18 10:48:34,141] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_setauth_usergp
[2022-02-18 10:48:37,769] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_usergp
[2022-02-18 10:48:41,473] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_usergp
[2022-02-18 10:48:54,252] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:51:20,993] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:51:22,779] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:51:24,061] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:51:24,898] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:51:25,719] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:51:26,581] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:51:27,506] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:51:31,432] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:51:32,003] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:51:32,785] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:51:33,561] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:51:36,578] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:51:39,712] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:51:42,477] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:51:45,486] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:51:48,354] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:51:51,337] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:51:54,195] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:51:57,181] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:52:00,019] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:52:02,837] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:52:05,650] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:52:08,522] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:52:28,567] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:52:31,535] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:52:34,418] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:52:37,415] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:55:44,517] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:55:46,168] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:55:47,003] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:55:47,818] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:55:48,664] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:55:49,504] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:55:50,390] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:55:54,280] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:55:54,764] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:55:55,529] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:55:56,284] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:55:59,241] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:56:01,994] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:56:04,813] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:56:07,730] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:56:10,571] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:56:13,502] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:56:16,411] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:56:19,276] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:56:22,079] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:56:24,961] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:56:27,787] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:56:30,702] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 10:56:50,734] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:56:53,583] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:56:56,470] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:56:59,498] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 10:57:26,924] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 10:57:30,136] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:57:33,263] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 10:57:34,856] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 10:57:34,946] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 10:57:43,289] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 10:57:43,429] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 10:57:43,484] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 10:58:16,121] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 10:58:30,767] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_auth
[2022-02-18 10:58:34,612] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_auth
[2022-02-18 10:58:36,836] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 10:58:37,903] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:58:39,579] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 10:58:41,206] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 10:58:41,324] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 10:58:49,850] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 10:58:49,983] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 10:58:50,038] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 10:58:54,420] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:58:55,000] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:58:55,820] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 10:58:56,654] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:58:57,495] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:58:58,233] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 10:58:59,171] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 10:59:03,106] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:59:03,605] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:59:04,358] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 10:59:05,152] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:59:08,156] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:59:11,119] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 10:59:13,993] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:59:16,852] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:59:19,656] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:59:22,433] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:59:25,311] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 10:59:28,211] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:59:31,053] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:59:34,006] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:59:36,790] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 10:59:39,778] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 11:00:00,087] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 11:00:02,984] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 11:00:05,932] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 11:00:08,936] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 11:00:36,957] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_usergp
[2022-02-18 11:00:40,101] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_setauth_usergp
[2022-02-18 11:00:43,918] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_usergp
[2022-02-18 11:00:47,747] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_usergp
[2022-02-18 11:00:53,760] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 11:00:57,894] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_user
[2022-02-18 11:01:07,186] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_user
[2022-02-18 11:01:11,903] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_active_user
[2022-02-18 11:01:18,230] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lock_user
[2022-02-18 11:01:23,593] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_unlock_user
[2022-02-18 11:01:29,142] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 11:01:51,741] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:01:54,736] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:01:57,853] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:02:04,181] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:02:10,567] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:02:16,834] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:02:23,127] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:02:29,536] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 11:02:35,791] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:02:42,007] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:02:48,295] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:02:54,543] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:03:00,809] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:03:07,067] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 11:03:13,006] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:03:18,713] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:03:24,626] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:03:30,498] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:03:36,458] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:03:42,328] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 11:03:46,130] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 11:06:29,637] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 11:06:36,768] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_user
[2022-02-18 11:06:46,011] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_user
[2022-02-18 11:06:50,762] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_active_user
[2022-02-18 11:06:57,037] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lock_user
[2022-02-18 11:06:57,917] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_unlock_user
[2022-02-18 11:07:39,473] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 11:08:40,050] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 11:08:46,191] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_user
[2022-02-18 11:08:55,352] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_user
[2022-02-18 11:09:00,152] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_active_user
[2022-02-18 11:09:06,402] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lock_user
[2022-02-18 11:09:11,867] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_unlock_user
[2022-02-18 11:09:17,189] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 11:09:46,912] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:09:53,306] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:09:59,855] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:10:06,399] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:10:12,902] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:10:19,514] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:10:26,095] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:10:32,631] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 11:10:39,124] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:10:45,379] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:10:51,649] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:10:58,145] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:11:04,576] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:11:10,974] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 11:11:17,019] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:11:22,675] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:11:28,542] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:11:34,359] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:11:40,210] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:11:46,203] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 11:11:50,037] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 11:15:57,103] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:16:03,944] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:16:10,466] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:16:17,121] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:16:23,567] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:16:30,161] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:16:36,618] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:16:43,187] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 11:16:49,686] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:16:56,059] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:17:02,417] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:17:08,785] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:17:15,167] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:17:21,595] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 11:17:28,188] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:17:33,740] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:17:39,636] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:17:45,434] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:17:51,321] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:17:57,233] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 11:18:01,049] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 11:18:04,814] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 11:40:10,195] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 11:40:19,498] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_auth
[2022-02-18 11:40:24,103] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_auth
[2022-02-18 11:40:28,808] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 11:40:29,894] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 11:40:31,580] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 11:40:33,192] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 11:40:33,292] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 11:40:41,705] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 11:40:41,820] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 11:40:41,924] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 11:40:46,318] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 11:40:46,924] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 11:40:47,822] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 11:40:48,663] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 11:40:49,574] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 11:40:50,420] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 11:40:51,316] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 11:40:55,221] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 11:40:55,756] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 11:40:56,475] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 11:40:57,281] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 11:41:00,347] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 11:41:03,274] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 11:41:06,252] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 11:41:09,242] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 11:41:12,107] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 11:41:15,060] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 11:41:18,012] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 11:41:20,903] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 11:41:23,668] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 11:41:26,467] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 11:41:29,435] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 11:41:32,256] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 11:41:52,182] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 11:41:54,982] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 11:41:57,885] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 11:42:00,832] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 11:42:10,687] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_usergp
[2022-02-18 11:42:14,004] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_setauth_usergp
[2022-02-18 11:42:17,258] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_usergp
[2022-02-18 11:42:21,165] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_usergp
[2022-02-18 11:42:25,816] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 11:42:32,651] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_user
[2022-02-18 11:42:41,980] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_user
[2022-02-18 11:42:46,712] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_active_user
[2022-02-18 11:42:53,041] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lock_user
[2022-02-18 11:42:58,328] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_unlock_user
[2022-02-18 11:43:03,769] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 11:43:26,731] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:43:29,696] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:43:34,749] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:43:41,353] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:43:47,867] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:43:54,396] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:44:00,918] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 11:44:07,381] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 11:44:13,925] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:44:20,324] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:44:26,816] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:44:33,359] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:44:39,853] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 11:44:46,345] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 11:44:52,901] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:44:58,913] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:45:04,664] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:45:10,547] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:45:16,400] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 11:45:22,257] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 11:45:26,070] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 13:40:28,522] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 13:40:54,755] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 13:42:18,961] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 13:42:32,595] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_auth
[2022-02-18 13:42:36,311] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_auth
[2022-02-18 13:42:38,509] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 13:42:39,584] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 13:42:41,236] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 13:42:42,843] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 13:42:42,910] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 13:42:51,332] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 13:42:51,441] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 13:42:51,498] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 13:42:55,858] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 13:42:56,464] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 13:42:57,240] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 13:42:58,074] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 13:42:58,889] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 13:42:59,724] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 13:43:00,645] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 13:43:04,591] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 13:43:05,095] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 13:43:05,852] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 13:43:06,632] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 13:43:09,627] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 13:43:12,475] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 13:43:15,450] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:43:18,368] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:43:21,225] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:43:24,159] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:43:26,980] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:43:29,886] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 13:43:32,667] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 13:43:35,525] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 13:43:38,341] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 13:43:41,144] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 13:44:01,377] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 13:44:04,285] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 13:44:07,111] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 13:44:10,060] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 13:44:38,451] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_usergp
[2022-02-18 13:44:42,316] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_setauth_usergp
[2022-02-18 13:44:46,287] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_usergp
[2022-02-18 13:44:50,182] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_usergp
[2022-02-18 13:44:56,234] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 13:45:16,484] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_user
[2022-02-18 13:45:23,944] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_user
[2022-02-18 13:45:27,793] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_active_user
[2022-02-18 13:45:31,570] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lock_user
[2022-02-18 13:45:35,364] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_unlock_user
[2022-02-18 13:45:39,148] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 13:45:52,959] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:45:59,420] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:46:05,695] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:46:12,323] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:46:18,859] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:46:25,343] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:46:31,766] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:46:38,230] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 13:46:44,759] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:46:51,264] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:46:57,710] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:47:04,208] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:47:10,689] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:47:17,190] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 13:47:23,803] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:47:29,781] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:47:35,626] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:47:41,640] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:47:47,564] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:47:53,469] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 13:47:57,349] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 13:52:17,262] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_auth
[2022-02-18 13:52:29,977] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_auth
[2022-02-18 13:52:33,819] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_auth
[2022-02-18 13:52:36,132] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_organization
[2022-02-18 13:52:37,250] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 13:52:38,976] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom
[2022-02-18 13:52:40,649] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_refresh_orgcom
[2022-02-18 13:52:40,737] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_edit
[2022-02-18 13:52:49,321] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_delete
[2022-02-18 13:52:49,430] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_refresh
[2022-02-18 13:52:49,508] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_orgcom
[2022-02-18 13:52:53,923] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 13:52:54,509] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 13:52:55,371] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2022-02-18 13:52:56,255] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 13:52:57,077] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 13:52:57,951] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2022-02-18 13:52:58,839] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2022-02-18 13:53:02,776] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 13:53:03,281] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 13:53:04,043] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2022-02-18 13:53:04,862] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 13:53:07,917] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 13:53:10,897] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add_abnormal
[2022-02-18 13:53:13,905] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:53:16,727] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:53:19,633] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:53:22,594] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:53:25,486] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add_adnormal
[2022-02-18 13:53:28,378] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 13:53:31,330] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 13:53:34,274] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 13:53:37,221] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add_abnormal
[2022-02-18 13:53:40,025] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 13:54:00,439] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 13:54:03,417] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 13:54:06,362] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 13:54:09,275] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit_abmormal
[2022-02-18 13:54:20,157] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_usergp
[2022-02-18 13:54:22,880] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_setauth_usergp
[2022-02-18 13:54:26,320] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_usergp
[2022-02-18 13:54:30,217] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_usergp
[2022-02-18 13:54:36,898] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_user
[2022-02-18 13:54:42,307] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_user
[2022-02-18 13:54:51,661] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_user
[2022-02-18 13:54:56,465] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_active_user
[2022-02-18 13:55:02,878] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lock_user
[2022-02-18 13:55:08,236] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_unlock_user
[2022-02-18 13:55:13,585] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_user
[2022-02-18 13:55:23,628] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:55:30,033] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:55:36,559] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:55:43,345] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:55:49,816] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:55:56,382] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:56:02,916] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror1
[2022-02-18 13:56:09,532] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_usernamerror2
[2022-02-18 13:56:16,019] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:56:22,475] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:56:28,793] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:56:35,213] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:56:41,753] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_mailerror
[2022-02-18 13:56:48,253] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_adduser_rfiderror
[2022-02-18 13:56:54,788] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:57:00,753] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:57:06,590] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:57:12,594] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:57:18,428] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edituser_mailerror
[2022-02-18 13:57:24,279] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror1
[2022-02-18 13:57:28,210] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_activeuser_passwderror2
[2022-02-18 13:59:20,239] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
[2022-02-18 13:59:21,446] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 13:59:25,056] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 13:59:27,460] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 13:59:29,873] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 13:59:32,309] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2022-02-18 13:59:34,050] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit
[2022-02-18 13:59:38,212] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 13:59:45,051] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 13:59:53,062] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 14:00:01,007] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 14:00:08,883] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search_cancel
[2022-02-18 14:03:30,109] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:03:32,469] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:03:34,971] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:03:37,404] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:03:39,852] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:03:42,367] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 14:03:44,822] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:03:47,294] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:03:49,791] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 14:03:53,295] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:03:57,326] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:04:01,523] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:04:06,555] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 14:07:38,929] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:07:41,392] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:07:43,979] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:07:46,404] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:07:48,778] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:07:51,236] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 14:07:53,665] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:07:56,158] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:07:58,571] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 14:08:05,136] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:08:20,492] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:08:24,697] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:08:31,843] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 14:13:42,935] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:13:47,633] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:14:36,531] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:14:39,020] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:14:41,577] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:14:43,978] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:14:46,365] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:14:48,885] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 14:14:54,974] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:14:57,424] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:14:59,858] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 14:15:07,496] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:15:12,578] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:15:17,731] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:15:26,010] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 14:19:03,007] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:19:06,605] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:19:09,118] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:19:11,612] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:19:14,011] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:19:16,483] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 14:19:19,999] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:19:22,463] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:19:24,914] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 14:19:32,363] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:19:37,754] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:19:46,666] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:19:54,938] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 14:23:17,482] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:23:55,161] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:23:59,656] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:24:04,113] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:24:08,767] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:24:13,183] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:24:17,772] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 14:24:23,361] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:24:27,871] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:24:32,304] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 14:24:38,120] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:24:44,169] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:24:53,845] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:25:03,032] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 14:28:54,932] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:28:59,670] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:29:42,882] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:29:47,420] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:29:51,854] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:29:56,269] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:30:00,811] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:30:05,245] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 14:30:10,660] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:30:15,080] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:30:19,396] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 14:30:25,189] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:30:32,271] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:30:43,322] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:30:56,804] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 14:33:58,583] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:34:03,270] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:34:35,398] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:34:39,951] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:34:44,461] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:34:48,951] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:34:53,330] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:34:57,841] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 14:35:03,370] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:35:07,737] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:35:12,158] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 14:35:17,997] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:35:25,299] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:35:36,221] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:38:49,865] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 14:38:54,467] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 14:38:58,969] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:39:03,507] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:39:08,057] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 14:39:12,564] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 14:39:17,990] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:39:22,522] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 14:39:27,026] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 14:39:32,924] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:39:40,063] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:39:50,775] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:40:01,107] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 14:42:26,269] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:42:31,027] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:42:45,088] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:42:51,847] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 14:46:25,733] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:46:34,121] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:46:41,330] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:46:48,125] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 14:49:16,890] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:49:21,637] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:49:38,343] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 14:53:53,725] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:54:04,249] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:54:50,104] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:55:01,809] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:56:10,581] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:56:20,892] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:57:12,532] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:57:24,051] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:58:47,433] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 14:58:52,257] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:00:31,456] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:00:36,257] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:15:04,247] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
[2022-02-18 15:15:15,084] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:15:20,009] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:15:24,754] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:15:32,093] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:15:37,377] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2022-02-18 15:15:39,785] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit
[2022-02-18 15:15:49,562] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:15:56,565] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:16:01,882] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:16:09,806] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:16:17,703] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search_cancel
[2022-02-18 15:16:22,508] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:16:33,596] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:18:33,895] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 15:18:38,265] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 15:18:43,020] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 15:18:47,619] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 15:18:51,984] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 15:18:56,394] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 15:19:01,830] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 15:19:06,218] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 15:19:10,790] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 15:19:16,797] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:19:27,074] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:19:37,216] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 15:20:05,232] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 15:21:21,913] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 15:21:28,649] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 15:21:33,231] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 15:21:37,647] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 15:21:42,121] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 15:21:46,712] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 15:21:52,326] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 15:21:56,695] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 15:22:01,231] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 15:22:07,189] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:22:15,235] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:22:23,272] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 15:22:30,514] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 15:24:40,574] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 15:24:45,390] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 15:25:07,564] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:25:49,081] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:26:31,291] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:27:32,351] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 15:27:33,767] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 15:38:52,000] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 15:39:03,397] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 15:39:28,177] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 15:39:36,058] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 15:39:43,851] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search
[2022-02-18 15:40:25,067] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit
[2022-02-18 15:41:06,564] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_relation
[2022-02-18 15:41:48,598] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_remove
[2022-02-18 15:42:18,535] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 15:42:25,168] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 15:42:33,395] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search
[2022-02-18 15:42:50,679] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit
[2022-02-18 15:42:53,292] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_relation
[2022-02-18 15:42:56,638] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_remove
[2022-02-18 15:43:00,025] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_delete
[2022-02-18 15:43:00,199] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search_cancel
[2022-02-18 15:43:37,098] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 15:43:41,838] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 15:43:46,512] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:44:19,255] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 15:44:23,278] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 15:44:27,416] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:44:31,356] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:44:35,467] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:44:39,654] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 15:44:44,851] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 15:44:49,947] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 15:44:54,658] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 15:44:58,515] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 15:45:02,417] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 15:45:06,381] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 15:45:08,789] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 15:45:11,994] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 15:45:14,470] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 15:45:16,940] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 15:47:45,727] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 15:47:50,519] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 15:47:55,244] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 15:47:59,920] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 15:48:25,123] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 15:48:28,834] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 15:48:38,336] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 15:48:41,731] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 15:49:37,028] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
[2022-02-18 15:49:49,481] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:49:54,104] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:49:58,851] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:50:03,522] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:50:08,264] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2022-02-18 15:50:13,151] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit
[2022-02-18 15:50:17,830] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:50:22,573] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:50:27,303] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:50:31,971] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:50:36,660] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search_cancel
[2022-02-18 15:51:18,432] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
[2022-02-18 15:51:24,676] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:51:46,113] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:51:50,635] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:51:55,108] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 15:51:59,670] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2022-02-18 15:52:01,389] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit
[2022-02-18 15:52:08,268] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:52:15,031] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:52:22,872] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:52:30,728] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 15:52:38,578] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search_cancel
[2022-02-18 15:52:58,219] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 15:53:02,913] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 15:53:07,519] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 15:53:12,108] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 15:53:16,818] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 15:53:21,238] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 15:53:26,794] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 15:53:31,445] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 15:53:36,122] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 15:53:42,080] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:53:50,135] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 15:53:58,308] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 15:54:05,688] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 15:54:44,927] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 15:54:49,233] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 15:54:53,555] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:54:57,707] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:55:01,959] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 15:55:06,125] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 15:55:14,995] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 15:55:18,917] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 15:55:23,689] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 15:55:27,742] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 15:55:31,711] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 15:55:39,363] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 15:55:41,905] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 15:55:45,183] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 15:55:47,680] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 15:55:50,251] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 15:56:00,384] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 15:56:03,588] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 15:56:10,705] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search
[2022-02-18 15:56:51,992] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit
[2022-02-18 15:56:55,809] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_relation
[2022-02-18 15:57:37,264] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_remove
[2022-02-18 15:58:18,595] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_delete
[2022-02-18 15:58:22,386] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search_cancel
[2022-02-18 15:58:27,321] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 15:58:31,313] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 15:58:38,801] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 15:58:42,657] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 16:00:11,481] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
[2022-02-18 16:00:20,097] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:00:26,009] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:00:30,530] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:00:34,868] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:00:39,304] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2022-02-18 16:00:40,925] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit
[2022-02-18 16:00:47,775] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:00:54,441] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:01:02,246] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:01:10,034] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:01:17,738] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search_cancel
[2022-02-18 16:01:37,007] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 16:01:41,422] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 16:01:45,930] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:01:50,356] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:01:54,740] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:01:59,081] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 16:02:04,452] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 16:02:08,897] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 16:02:13,524] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 16:02:19,409] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 16:02:27,274] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 16:02:36,789] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 16:02:44,392] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 16:03:07,362] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 16:03:11,431] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 16:03:15,646] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:03:19,852] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:03:24,006] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:03:28,289] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 16:03:36,053] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 16:03:39,949] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 16:03:44,564] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:03:48,437] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:03:52,497] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 16:03:56,739] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 16:03:59,209] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 16:04:02,383] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:04:04,777] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:04:07,204] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 16:04:17,521] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 16:04:20,690] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 16:04:27,691] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search
[2022-02-18 16:04:35,481] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit
[2022-02-18 16:04:38,129] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_relation
[2022-02-18 16:04:41,485] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_remove
[2022-02-18 16:04:44,868] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_delete
[2022-02-18 16:04:45,085] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search_cancel
[2022-02-18 16:04:51,902] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 16:05:12,055] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 16:05:19,463] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 16:05:23,192] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 16:06:36,513] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 16:06:41,191] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 16:06:50,469] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 16:06:53,777] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 16:08:57,280] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
[2022-02-18 16:09:03,500] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:09:09,147] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:09:13,665] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:09:18,083] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:09:22,456] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2022-02-18 16:09:24,104] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit
[2022-02-18 16:09:30,984] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:09:37,666] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:09:45,415] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:09:53,232] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:10:00,982] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search_cancel
[2022-02-18 16:10:20,189] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 16:10:24,704] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 16:10:29,232] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:10:33,614] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:10:38,083] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:10:42,505] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 16:10:48,074] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 16:10:52,719] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 16:10:57,301] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 16:11:03,298] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 16:11:11,250] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 16:11:19,347] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 16:11:26,710] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 16:11:49,248] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 16:11:53,240] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 16:11:57,429] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:12:01,587] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:12:05,757] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:12:09,922] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 16:12:17,677] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 16:12:21,595] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 16:12:26,163] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:12:30,229] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:12:34,261] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 16:12:38,491] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 16:12:40,990] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 16:12:44,267] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:12:46,761] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:12:49,352] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 16:12:59,401] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 16:13:02,540] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 16:13:09,602] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search
[2022-02-18 16:13:23,278] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit
[2022-02-18 16:13:25,721] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_relation
[2022-02-18 16:13:29,049] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_remove
[2022-02-18 16:13:32,346] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_delete
[2022-02-18 16:13:32,508] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search_cancel
[2022-02-18 16:13:39,299] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 16:13:59,371] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 16:14:12,922] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 16:14:16,506] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 16:19:46,108] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 16:19:50,715] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 16:20:00,190] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 16:20:03,716] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 16:21:40,189] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 16:21:44,427] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 16:21:48,676] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:21:52,786] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:21:56,879] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:22:01,071] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 16:22:05,209] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 16:22:09,159] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 16:22:13,918] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:22:17,970] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:22:22,018] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 16:22:26,135] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 16:22:28,503] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 16:22:31,645] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:22:34,138] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:22:36,586] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 16:23:16,623] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
[2022-02-18 16:23:25,881] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:23:31,580] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:23:36,154] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:23:40,608] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:23:45,060] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2022-02-18 16:23:46,715] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit
[2022-02-18 16:23:53,675] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:24:00,484] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:24:08,292] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:24:16,065] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:24:23,829] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search_cancel
[2022-02-18 16:24:43,797] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 16:24:48,299] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 16:24:52,719] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:24:57,133] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:25:01,590] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:25:05,988] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 16:25:11,397] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 16:25:15,847] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 16:25:20,492] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 16:25:26,500] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 16:25:34,438] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 16:25:42,306] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 16:25:49,746] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 16:26:19,004] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 16:26:23,166] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 16:26:27,329] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:26:31,288] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:26:35,313] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:26:39,355] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 16:26:43,346] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 16:26:47,347] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 16:26:51,937] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:26:55,970] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:26:59,914] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 16:27:03,932] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 16:27:06,349] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 16:27:09,485] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:27:11,893] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:27:14,335] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 16:27:24,324] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 16:27:28,482] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 16:27:36,290] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search
[2022-02-18 16:27:56,181] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit
[2022-02-18 16:27:57,760] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_relation
[2022-02-18 16:28:00,987] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_remove
[2022-02-18 16:28:04,327] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_delete
[2022-02-18 16:28:04,532] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search_cancel
[2022-02-18 16:28:11,483] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 16:28:32,263] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 16:28:39,707] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 16:28:43,598] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 16:30:14,023] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 16:30:16,586] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 16:30:25,820] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 16:30:29,102] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 16:30:50,271] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
[2022-02-18 16:31:01,507] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:31:07,168] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:31:11,625] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:31:16,069] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:31:20,483] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2022-02-18 16:31:22,131] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit
[2022-02-18 16:31:29,152] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:31:35,821] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:31:43,633] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:31:51,374] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 16:31:59,238] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search_cancel
[2022-02-18 16:32:18,975] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 16:32:23,416] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 16:32:28,095] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:32:32,491] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:32:36,871] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 16:32:41,386] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 16:32:46,995] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 16:32:51,557] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 16:32:56,179] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 16:33:01,945] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 16:33:09,836] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 16:33:17,714] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 16:33:25,284] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 16:34:35,039] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 16:35:11,383] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 16:35:15,800] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:35:19,926] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:35:24,101] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:35:28,330] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 16:35:32,275] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 16:35:36,382] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 16:35:41,183] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:35:45,237] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:35:49,310] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 16:35:57,346] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 16:35:59,877] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 16:36:03,138] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:36:05,772] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:36:08,294] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 16:36:18,778] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 16:36:22,972] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 16:36:31,300] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search
[2022-02-18 16:36:48,679] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit
[2022-02-18 16:36:51,270] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_relation
[2022-02-18 16:36:54,533] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_remove
[2022-02-18 16:36:57,940] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_delete
[2022-02-18 16:36:58,170] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search_cancel
[2022-02-18 16:37:08,070] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 16:37:10,734] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 16:37:20,189] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 16:37:23,634] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
[2022-02-18 16:51:59,240] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 16:52:03,441] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 16:52:07,640] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:52:11,723] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:52:16,032] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:52:20,313] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 16:52:24,500] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 16:52:28,533] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 16:52:33,257] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:52:37,298] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:52:41,371] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 16:52:50,632] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 16:53:32,187] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 16:53:39,625] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:53:42,131] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:53:44,658] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 16:56:42,525] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 16:56:46,558] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 16:56:50,788] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:56:54,954] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:56:59,014] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 16:57:03,061] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 16:57:07,207] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 16:57:11,331] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 16:57:16,065] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:57:20,216] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 16:57:24,206] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 16:57:30,298] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 16:57:32,697] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 16:57:35,913] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:57:38,401] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 16:57:40,808] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 16:59:43,528] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_login_Device
[2022-02-18 16:59:49,795] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 16:59:55,830] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 17:00:00,401] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 17:00:04,861] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add
[2022-02-18 17:00:09,298] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search
[2022-02-18 17:00:10,917] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit
[2022-02-18 17:00:17,799] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 17:00:24,523] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 17:00:32,277] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 17:00:40,096] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_delete
[2022-02-18 17:00:48,046] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_search_cancel
[2022-02-18 17:01:07,647] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_001
[2022-02-18 17:01:12,256] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_002
[2022-02-18 17:01:17,029] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 17:01:21,575] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 17:01:26,071] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_003
[2022-02-18 17:01:30,535] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_code_abnormal_004
[2022-02-18 17:01:35,951] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 17:01:40,506] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_001
[2022-02-18 17:01:45,193] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_add_name_abnormal_002
[2022-02-18 17:01:51,120] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 17:01:59,149] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_001
[2022-02-18 17:02:07,108] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_002
[2022-02-18 17:02:14,632] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_device_edit_name_abnormal_003
[2022-02-18 17:02:43,964] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_001
[2022-02-18 17:02:48,041] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_002
[2022-02-18 17:02:52,199] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 17:02:56,298] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 17:03:00,434] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_003
[2022-02-18 17:03:04,560] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_code_abnormal_004
[2022-02-18 17:03:08,705] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_001
[2022-02-18 17:03:12,731] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_002
[2022-02-18 17:03:17,401] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 17:03:21,388] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_name_name_abnormal_003
[2022-02-18 17:03:25,462] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add_name_abnormal_004
[2022-02-18 17:03:31,595] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_001
[2022-02-18 17:03:34,066] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_002
[2022-02-18 17:03:37,242] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 17:03:39,736] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_code_abnormal_003
[2022-02-18 17:03:42,255] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit_name_abnormal_004
[2022-02-18 17:03:52,342] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_manage
[2022-02-18 17:03:56,565] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_add
[2022-02-18 17:04:04,686] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search
[2022-02-18 17:04:07,272] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_edit
[2022-02-18 17:04:09,752] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_relation
[2022-02-18 17:04:13,066] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_remove
[2022-02-18 17:04:16,363] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_delete
[2022-02-18 17:04:16,571] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workercenter_search_cancel
[2022-02-18 17:04:26,316] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_workstation
[2022-02-18 17:04:28,803] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_workstation
[2022-02-18 17:04:38,144] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_workstation
[2022-02-18 17:04:41,643] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_workstation
